const express = require("express");
const router = express.Router();
const feedRouter = require("./routes/product-feeds");
const offerRouter = require("./routes/offer");
const navigationRouter = require("./routes/navigation");
const itemsRouteer = require("./routes/items");
const inventoryRouter = require("./routes/inventory");
const fileRouter = require("./routes/file");
const profileRouter = require("./routes/profile");
const shipmentRouter = require("./routes/shipments");
const paymentRouter = require("./routes/payment");
const sellerRouter = require("./routes/seller/router");
const orderRouter = require("./routes/order");
const authRouter = require("./routes/auth");
const adminRouter = require("./routes/admin/router");
const publicRouter = require("./routes/public/router");
const directoryRouter = require("./routes/directory/router");

const authenticateSeller = require("./middleware/authenticateSeller");
const shopMiddleware = require("./middleware/shopMiddleware");
const adminAuthMiddleware = require("./middleware/adminAuthMiddleware");
const publicMiddleware = require("./middleware/publicMiddleware");

router.use("/auth", authRouter);
router.use("/public", publicMiddleware, publicRouter);
router.use("/admin", adminAuthMiddleware, adminRouter);
router.use("/feeds", feedRouter);
router.use("/offers", authenticateSeller, offerRouter);
router.use("/navigation", authenticateSeller, navigationRouter);
router.use("/items", authenticateSeller, itemsRouteer);
router.use("/inventory", authenticateSeller, inventoryRouter);
router.use("/files", authenticateSeller, fileRouter);
router.use("/orders", orderRouter);
router.use("/profiles", profileRouter);
router.use("/shipments", shipmentRouter);
router.use("/payments", paymentRouter);
router.use("/seller/:sellerKey", shopMiddleware, sellerRouter);
router.use("/directory", directoryRouter);

module.exports = router;
