const express = require("express");
const router = express.Router();

const accountRouter = require("./routes/account");
const userRouter = require("./routes/user");
const organizationRouter = require("./routes/organization");
const storefrontRouter = require("./routes/storefront");
const storefrontRegionsRouter = require("./routes/storefront-locale");
const storeCategoryRouter = require("./routes/store-categories");
const paymentAccountRouter = require("./routes/payment-accounts");
const productsRouter = require("./routes/product");
const storefrontProductSegmentRouter = require("./routes/storefront-product-segment");
const storefrontTemplateRouter = require("./routes/storefront-templates");
const storefrontTemplateFieldsRouter = require("./routes/storefront-template-fields");
const storefrontFieldsRouter = require("./routes/storefront-fields");
const brandsRouter = require("./routes/brands");
const storefrontBrandsRouter = require("./routes/storefront-brands");
const productPropertiesRouter = require("./routes/product-properties");
const productPropertyOptionsRouter = require("./routes/product-property-options");
const productVariantsRouter = require("./routes/product-variants");
const productMediaRouter = require("./routes/product-media");
const mediaRouter = require("./routes/media");
const storeCollectionsRouter = require("./routes/storefront-collections");
const storefrontCollectionProducts = require("./routes/storefront-collection-products");
const listPriceRouter = require("./routes/list-prices");
const offersRouter = require("./routes/offers");
const inventoryLocationsRouter = require("./routes/inventory-locations");

router.use("/accounts", accountRouter);
router.use("/brands", brandsRouter);
router.use("/users", userRouter);
router.use("/organizations", organizationRouter);
router.use("/storefront", storefrontRouter);
router.use("/storefront-regions", storefrontRegionsRouter);
router.use("/storefront-product-segments", storefrontProductSegmentRouter);
router.use("/storefront-templates", storefrontTemplateRouter);
router.use("/storefront-fields", storefrontFieldsRouter);
router.use("/storefront-template-fields", storefrontTemplateFieldsRouter);
router.use("/storefront-brands", storefrontBrandsRouter);
router.use("/storefront-collections", storeCollectionsRouter);
router.use("/storefront-collection-products", storefrontCollectionProducts);
router.use("/store-categories", storeCategoryRouter);
router.use("/payment-accounts", paymentAccountRouter);
router.use("/products", productsRouter);
router.use("/product-properties", productPropertiesRouter);
router.use("/product-property-options", productPropertyOptionsRouter);
router.use("/product-variants", productVariantsRouter);
router.use("/product-media", productMediaRouter);
router.use("/list-prices", listPriceRouter);
router.use("/offers", offersRouter);
router.use("/media", mediaRouter);
router.use("/inventory-locations", inventoryLocationsRouter);

module.exports = router;
